[package]
name = "snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23.2"
rand = "0.8.5"
tui = "0.18.0"
clap = { version = "3.1.18", features = ["derive"] }
